// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RefreshTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenRefresh         string   `protobuf:"bytes,2,opt,name=tokenRefresh,proto3" json:"tokenRefresh,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshTokenRequest) GetTokenRefresh() string {
	if m != nil {
		return m.TokenRefresh
	}
	return ""
}

type RefreshTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type SignInRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignInResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SignInResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type SignUpRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpRequest) Reset()         { *m = SignUpRequest{} }
func (m *SignUpRequest) String() string { return proto.CompactTextString(m) }
func (*SignUpRequest) ProtoMessage()    {}
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *SignUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpRequest.Unmarshal(m, b)
}
func (m *SignUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpRequest.Marshal(b, m, deterministic)
}
func (m *SignUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpRequest.Merge(m, src)
}
func (m *SignUpRequest) XXX_Size() int {
	return xxx_messageInfo_SignUpRequest.Size(m)
}
func (m *SignUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpRequest proto.InternalMessageInfo

func (m *SignUpRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *SignUpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignUpRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignUpRequest) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

type DeleteRequest struct {
	Login                string   `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type AddClaimsRequest struct {
	Login                string            `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Claims               map[string]string `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddClaimsRequest) Reset()         { *m = AddClaimsRequest{} }
func (m *AddClaimsRequest) String() string { return proto.CompactTextString(m) }
func (*AddClaimsRequest) ProtoMessage()    {}
func (*AddClaimsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *AddClaimsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddClaimsRequest.Unmarshal(m, b)
}
func (m *AddClaimsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddClaimsRequest.Marshal(b, m, deterministic)
}
func (m *AddClaimsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddClaimsRequest.Merge(m, src)
}
func (m *AddClaimsRequest) XXX_Size() int {
	return xxx_messageInfo_AddClaimsRequest.Size(m)
}
func (m *AddClaimsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddClaimsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddClaimsRequest proto.InternalMessageInfo

func (m *AddClaimsRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *AddClaimsRequest) GetClaims() map[string]string {
	if m != nil {
		return m.Claims
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type DeleteClaimsRequest struct {
	Login                string            `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Claims               map[string]string `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteClaimsRequest) Reset()         { *m = DeleteClaimsRequest{} }
func (m *DeleteClaimsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteClaimsRequest) ProtoMessage()    {}
func (*DeleteClaimsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *DeleteClaimsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClaimsRequest.Unmarshal(m, b)
}
func (m *DeleteClaimsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClaimsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteClaimsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClaimsRequest.Merge(m, src)
}
func (m *DeleteClaimsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteClaimsRequest.Size(m)
}
func (m *DeleteClaimsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClaimsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClaimsRequest proto.InternalMessageInfo

func (m *DeleteClaimsRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *DeleteClaimsRequest) GetClaims() map[string]string {
	if m != nil {
		return m.Claims
	}
	return nil
}

type ValidateToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateToken) Reset()         { *m = ValidateToken{} }
func (m *ValidateToken) String() string { return proto.CompactTextString(m) }
func (*ValidateToken) ProtoMessage()    {}
func (*ValidateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *ValidateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateToken.Unmarshal(m, b)
}
func (m *ValidateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateToken.Marshal(b, m, deterministic)
}
func (m *ValidateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateToken.Merge(m, src)
}
func (m *ValidateToken) XXX_Size() int {
	return xxx_messageInfo_ValidateToken.Size(m)
}
func (m *ValidateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateToken.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateToken proto.InternalMessageInfo

func (m *ValidateToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*RefreshTokenRequest)(nil), "protocol.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "protocol.RefreshTokenResponse")
	proto.RegisterType((*SignInRequest)(nil), "protocol.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "protocol.SignInResponse")
	proto.RegisterType((*SignUpRequest)(nil), "protocol.SignUpRequest")
	proto.RegisterType((*DeleteRequest)(nil), "protocol.DeleteRequest")
	proto.RegisterType((*AddClaimsRequest)(nil), "protocol.AddClaimsRequest")
	proto.RegisterMapType((map[string]string)(nil), "protocol.AddClaimsRequest.ClaimsEntry")
	proto.RegisterType((*EmptyResponse)(nil), "protocol.EmptyResponse")
	proto.RegisterType((*DeleteClaimsRequest)(nil), "protocol.DeleteClaimsRequest")
	proto.RegisterMapType((map[string]string)(nil), "protocol.DeleteClaimsRequest.ClaimsEntry")
	proto.RegisterType((*ValidateToken)(nil), "protocol.ValidateToken")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0xaf, 0xd2, 0x30,
	0x18, 0xcd, 0x18, 0x4e, 0xf8, 0x60, 0x4a, 0x0a, 0x89, 0xcb, 0x12, 0x0d, 0x69, 0x82, 0xc1, 0x97,
	0x3d, 0xe0, 0x8b, 0x62, 0x62, 0x5c, 0x14, 0x13, 0x4d, 0x8c, 0x66, 0x88, 0xef, 0x93, 0x55, 0x58,
	0x18, 0xeb, 0x5c, 0x3b, 0x0c, 0xbf, 0xc5, 0x47, 0x9f, 0xfc, 0x97, 0x37, 0xb4, 0xdb, 0xe8, 0xb8,
	0x8c, 0xdc, 0xdc, 0x7b, 0x9f, 0xd6, 0x73, 0xbe, 0xef, 0x3b, 0x3d, 0xed, 0x4e, 0x0a, 0xe0, 0x67,
	0x7c, 0xed, 0x24, 0x29, 0xe5, 0x14, 0xb5, 0xc4, 0x67, 0x49, 0x23, 0xfc, 0x15, 0xfa, 0x1e, 0xf9,
	0x95, 0x12, 0xb6, 0xfe, 0x4e, 0x37, 0x24, 0xf6, 0xc8, 0xef, 0x8c, 0x30, 0x8e, 0x06, 0xf0, 0x80,
	0x1f, 0xb0, 0xa5, 0x0d, 0xb5, 0x71, 0xdb, 0x93, 0x00, 0x61, 0xe8, 0x72, 0xd9, 0x25, 0x26, 0xac,
	0x86, 0x28, 0x56, 0x38, 0xfc, 0x0d, 0x06, 0x55, 0x41, 0x96, 0xd0, 0x98, 0x91, 0x7a, 0xc5, 0x54,
	0xe9, 0x2e, 0x14, 0x55, 0x0e, 0xbb, 0x60, 0xce, 0xc3, 0x55, 0xfc, 0x49, 0x35, 0x17, 0xd1, 0x55,
	0x58, 0x4a, 0x09, 0x80, 0x6c, 0x68, 0x25, 0x3e, 0x63, 0x7f, 0x68, 0x1a, 0xe4, 0x32, 0x25, 0xc6,
	0x9f, 0xe1, 0x51, 0x21, 0x71, 0x67, 0x3b, 0x54, 0xda, 0x59, 0x24, 0xb7, 0xb6, 0x83, 0x10, 0x34,
	0x63, 0x7f, 0x4b, 0x2c, 0x5d, 0xf0, 0x62, 0x8d, 0x2c, 0x78, 0xc8, 0xb2, 0x54, 0xd0, 0x4d, 0x41,
	0x17, 0x10, 0x8f, 0xc0, 0xfc, 0x40, 0x22, 0xc2, 0xc9, 0xc5, 0x0d, 0xf1, 0x3f, 0x0d, 0x7a, 0x6e,
	0x10, 0xbc, 0x8f, 0xfc, 0x70, 0xcb, 0x2e, 0x7b, 0x7b, 0x0b, 0xc6, 0x52, 0xb4, 0x59, 0x8d, 0xa1,
	0x3e, 0xee, 0x4c, 0x9e, 0x3b, 0x45, 0x1e, 0x9c, 0x53, 0x05, 0x47, 0xa2, 0x59, 0xcc, 0xd3, 0xbd,
	0x97, 0x4f, 0xd9, 0xaf, 0xa1, 0xa3, 0xd0, 0xa8, 0x07, 0xfa, 0x86, 0xec, 0xf3, 0x2d, 0x0e, 0xcb,
	0xc3, 0xb6, 0x3b, 0x3f, 0xca, 0x48, 0x7e, 0x72, 0x09, 0xa6, 0x8d, 0x57, 0x1a, 0x7e, 0x0c, 0xe6,
	0x6c, 0x9b, 0xf0, 0x7d, 0xf1, 0x23, 0xf0, 0x7f, 0x0d, 0xfa, 0xf2, 0x78, 0x37, 0x71, 0xee, 0x9e,
	0x38, 0x7f, 0x71, 0x74, 0x7e, 0x46, 0xe4, 0xbe, 0xcd, 0x8f, 0xc0, 0xfc, 0xe1, 0x47, 0x61, 0xe0,
	0x73, 0x22, 0xb2, 0x70, 0x3e, 0x45, 0x93, 0xbf, 0x3a, 0x74, 0xdc, 0x8c, 0xaf, 0xe7, 0x24, 0xdd,
	0x85, 0x4b, 0x82, 0xde, 0x80, 0x21, 0xd3, 0x87, 0x9e, 0x1c, 0xed, 0x56, 0x22, 0x6d, 0x5b, 0xd7,
	0x0b, 0x79, 0x50, 0xa7, 0x72, 0x78, 0x91, 0x9c, 0x0e, 0x97, 0x01, 0xb4, 0x95, 0x42, 0xe5, 0x6e,
	0xd1, 0x47, 0xe8, 0xaa, 0xb7, 0x82, 0x9e, 0x5e, 0xbc, 0xad, 0x7a, 0x9d, 0x29, 0x18, 0xb2, 0x5f,
	0xf5, 0x50, 0xc9, 0x64, 0xfd, 0xec, 0x3b, 0x68, 0x97, 0x99, 0x42, 0x76, 0x7d, 0xd0, 0xea, 0x15,
	0xbe, 0x40, 0x57, 0x7d, 0x51, 0xd4, 0x53, 0x9c, 0x79, 0xba, 0xec, 0x67, 0x75, 0x65, 0x29, 0xf7,
	0xd3, 0x10, 0xe5, 0x97, 0x57, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xea, 0xe9, 0xc6, 0x10, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteClaims(ctx context.Context, in *DeleteClaimsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	AddClaims(ctx context.Context, in *AddClaimsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/protocol.AuthService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.AuthService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) DeleteClaims(ctx context.Context, in *DeleteClaimsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.AuthService/DeleteClaims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.AuthService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AddClaims(ctx context.Context, in *AddClaimsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/protocol.AuthService/AddClaims", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/protocol.AuthService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	SignUp(context.Context, *SignUpRequest) (*EmptyResponse, error)
	DeleteClaims(context.Context, *DeleteClaimsRequest) (*EmptyResponse, error)
	Delete(context.Context, *DeleteRequest) (*EmptyResponse, error)
	AddClaims(context.Context, *AddClaimsRequest) (*EmptyResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAuthServiceServer) SignUp(ctx context.Context, req *SignUpRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (*UnimplementedAuthServiceServer) DeleteClaims(ctx context.Context, req *DeleteClaimsRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClaims not implemented")
}
func (*UnimplementedAuthServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedAuthServiceServer) AddClaims(ctx context.Context, req *AddClaimsRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddClaims not implemented")
}
func (*UnimplementedAuthServiceServer) RefreshToken(ctx context.Context, req *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AuthService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AuthService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_DeleteClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).DeleteClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AuthService/DeleteClaims",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).DeleteClaims(ctx, req.(*DeleteClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AuthService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AddClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AddClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AuthService/AddClaims",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AddClaims(ctx, req.(*AddClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AuthService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _AuthService_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _AuthService_SignUp_Handler,
		},
		{
			MethodName: "DeleteClaims",
			Handler:    _AuthService_DeleteClaims_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AuthService_Delete_Handler,
		},
		{
			MethodName: "AddClaims",
			Handler:    _AuthService_AddClaims_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthService_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
